# Generated by Django 5.1.3 on 2025-02-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htmlpart', '0003_file_teacher_results_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='fingerprints',
            field=models.JSONField(null=True),
        ),
    ]
