# Generated by Django 5.1.3 on 2025-02-27 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('htmlpart', '0004_file_fingerprints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='fingerprints',
        ),
    ]
