# Generated by Django 5.1.3 on 2025-02-28 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('htmlpart', '0006_file_fingerprints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='fingerprints',
        ),
    ]
