# Generated by Django 5.1.3 on 2025-02-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htmlpart', '0007_remove_file_fingerprints'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='fingerprints',
            field=models.JSONField(default=list),
        ),
    ]
