# Generated by Django 5.1.3 on 2025-03-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htmlpart', '0008_file_fingerprints'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='text_positions',
            field=models.JSONField(default=list),
        ),
    ]
