# Generated by Django 5.1.3 on 2025-03-01 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('htmlpart', '0009_file_text_positions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='text_positions',
        ),
    ]
