# Generated by Django 5.1.3 on 2025-03-02 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htmlpart', '0011_file_text_positions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='fingerprints',
        ),
        migrations.RemoveField(
            model_name='file',
            name='text_positions',
        ),
        migrations.AddField(
            model_name='file',
            name='credential_fingerprints',
            field=models.JSONField(default=list),
        ),
    ]
