# Generated by Django 5.1.3 on 2025-03-03 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htmlpart', '0012_remove_file_fingerprints_remove_file_text_positions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='credential_fingerprints',
        ),
        migrations.AddField(
            model_name='file',
            name='fingerprints',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='file',
            name='text_positions',
            field=models.JSONField(default=list),
        ),
    ]
