# Generated by Django 5.1.3 on 2025-03-04 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('htmlpart', '0015_remove_file_credential_fingerprints_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='text_positions',
        ),
    ]
