# Generated by Django 5.1.3 on 2025-03-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htmlpart', '0016_remove_file_text_positions'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='text_positions',
            field=models.JSONField(default=list),
        ),
    ]
