# Generated by Django 5.1.3 on 2025-03-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htmlpart', '0018_remove_file_text_positions'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='normalized_words',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='file',
            name='original_words',
            field=models.JSONField(default=list),
        ),
    ]
