# Generated by Django 5.1.3 on 2025-03-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htmlpart', '0019_file_normalized_words_file_original_words'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='normalized_words',
        ),
        migrations.RemoveField(
            model_name='file',
            name='original_words',
        ),
        migrations.AddField(
            model_name='file',
            name='text_positions',
            field=models.JSONField(default=list),
        ),
    ]
