# Generated by Django 5.1.3 on 2025-03-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htmlpart', '0020_remove_file_normalized_words_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='text_positions',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
