# Generated by Django 5.1.3 on 2025-03-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htmlpart', '0021_alter_file_text_positions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='fingerprints',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='text_positions',
            field=models.JSONField(default=list),
        ),
    ]
