# Generated by Django 5.1.3 on 2025-03-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htmlpart', '0024_alter_file_fingerprints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='fingerprints',
            field=models.JSONField(default=list),
        ),
    ]
